version: '3'

services:
    postgresql:
        image: postgres:15.2-alpine3.17
        environment:
            POSTGRES_DB: postgresql
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - '5432:5432'

    pgadminAnalytics:
        container_name: pgadminAnalytics
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - 5050:80
        depends_on:
            - postgresql
