name: Intégration continue & déploiment continue en dev

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  deploiement:
    name: Deploiement
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Utilisation de Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installation des dépendances
        run: npm ci
      - name: Déploiement de l'application
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.server_dev }}
          username: ${{ secrets.username_dev }}
          password: ${{ secrets.password_dev }}